version: "3"
services:
  server:
    # image: server:local
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm run dev"
    env_file:
      - ./env/.env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ./env/.env

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/data

volumes:
  # redis:
  #   driver: local
  database:
