version: "3"
services:
  nestjs-example:
    # image: nestjs-example:local
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "yarn dev"
    env_file:
      - ./env/.env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  database:
