version: "3"
services:
  nestjs-example:
    container_name: nestjs-example
    image: nestjs-example:local
    build:
      context: ./
      dockerfile: ./deployments/docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm i && npm run start:dev"
    env_file:
      - ./env/.env
